Add loading of .env file in ragstack-e2e-tests
datastax/ragstack-ai pull request #226
Opened 2024-01-24 14:39 UTC by cbornet

2024-01-24 14:59 UTC, nicoloboschi requested changes

2024-01-24 14:59 UTC, nicoloboschi commented on ragstack-e2e-tests/pyproject.toml
> +python-dotenv = "^1.0.1"
Also langchain master and friends?

2024-01-24 21:13 UTC, cbornet commented on ragstack-e2e-tests/pyproject.toml
> +python-dotenv = "^1.0.1"
Yes. Done.

2024-01-25 09:28 UTC, nicoloboschi approved these changes

2024-01-25 09:28 UTC, merged