[ref] simplify astra collection cleanup
datastax/ragstack-ai pull request #250
Opened 2024-01-29 21:00 UTC by jordanrfrazier

We still see some errors like
```
ValueError: API Exception while running bulk insertion: {'errors': [{'message': 'Collection does not exist, collection name: documents_b00f7c83', 'errorCode': 'COLLECTION_NOT_EXIST'}]}

```

I don't think this PR will fix those (if they even are a result of our test cleanup logic), but this should simplify the cleanup a bit anyway, and might help since it removes at least one unnecessary delete_collection call.

2024-01-29 21:05 UTC, jordanrfrazier commented on ragstack-e2e-tests/e2e_tests/test_utils/astradb_vector_store_handler.py
> -        self.delete_collection_handler.run_delete(self.astra_ref.collection)
Actually, was this (incorrectly) deleting the collection we just created for the purposes of the test?

And later on when we reassigned the `self.astra_ref.collection = .. `, how is that new collection being created?

2024-01-30 08:50 UTC, nicoloboschi requested changes

2024-01-30 08:50 UTC, nicoloboschi commented on ragstack-e2e-tests/e2e_tests/test_utils/astradb_vector_store_handler.py
> +        self.delete_collection_handler.run_delete(self.astra_ref.collection)
some tests use more than one collection, for example for the chat memory

2024-01-30 08:50 UTC, nicoloboschi commented on ragstack-e2e-tests/e2e_tests/test_utils/astradb_vector_store_handler.py
> -        logging.info("Ensuring astra env is clean")
the problem with this approach is that if a collection deletion is in progress, the get_collections won't return it. so we could end up with the same issue we have now

2024-01-30 15:15 UTC, closed without merging